# Permalinks
permalink:           pretty

# Setup
title:               GoReleaser
tagline:             'Deliver Go binaries as fast and easily as possible '
description:         'A GitHub release tool for <a href="https://golang.org" target="_blank">Go</a> binaries with built-in support for serveral platforms, Homebrew, and CI tools'
url:                 https://github.com/goreleaser/goreleaser.github.io
baseurl:             ''
github:
  projectUrl: https://github.com/goreleaser/goreleaser
  pageUrl: https://github.com/goreleaser/goreleaser.github.io

# About/contact
author:
  name:              Carlos Becker
  url:               carlosbecker.com
  email:             root@carlosbecker.com

# Custom vars
version:             1.0.0
